# Generated by Django 3.2.25 on 2025-03-05 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('job_frequency', models.CharField(max_length=10)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_type_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor_Device_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_group', models.CharField(blank=True, max_length=100, null=True)),
                ('device_name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('port', models.CharField(blank=True, max_length=100, null=True)),
                ('plant', models.CharField(blank=True, max_length=50, null=True)),
                ('enable', models.CharField(default='Y', max_length=1)),
                ('stop_before', models.CharField(blank=True, max_length=20, null=True)),
                ('status_update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('attr1', models.CharField(blank=True, max_length=500, null=True)),
                ('attr2', models.CharField(blank=True, max_length=500, null=True)),
                ('attr3', models.CharField(blank=True, max_length=500, null=True)),
                ('attr4', models.CharField(blank=True, max_length=500, null=True)),
                ('attr5', models.CharField(blank=True, max_length=500, null=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_list_device_type', to='spiderweb.device_type')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monitor_type_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor_Status',
            fields=[
                ('status_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('desc', models.CharField(max_length=200)),
                ('ref_url', models.CharField(blank=True, max_length=500, null=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='check_status_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor_Device_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice_flag', models.BooleanField(blank=True, null=True)),
                ('recover_msg', models.BooleanField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_device', to='spiderweb.monitor_device_list')),
                ('status_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='check_log_status', to='spiderweb.monitor_status')),
            ],
        ),
        migrations.AddField(
            model_name='monitor_device_list',
            name='monitor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_list_monitor_type', to='spiderweb.monitor_type'),
        ),
        migrations.AddField(
            model_name='monitor_device_list',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monitor_list_status', to='spiderweb.monitor_status'),
        ),
        migrations.AddField(
            model_name='monitor_device_list',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monitor_list_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
